"use strict";
/* 覆盖层显示逻辑(v1.8):选技以外什么都不画;一键隐藏只藏显示。用假 DOM/canvas 跑 overlay.html 里的脚本。 */
const fs = require("fs"), path = require("path");
const html = fs.readFileSync(path.join(__dirname, "..", "overlay.html"), "utf8"), code = html.split("<script>")[1].split("</script>")[0];
require("../frames.js");   // overlay.html 现在从 frames.js 取画框代码(挂在 globalThis.ADFrames)
const els = {}, el = id => els[id] = els[id] || { id, textContent: "", style: {} };
let drawn = 0; const ctx = new Proxy({}, { get: (t, k) => k === "measureText" ? () => ({ width: 100 }) : (k === "strokeRect" || k === "fillText") ? () => { drawn++; } : (typeof t[k] !== "undefined" ? t[k] : () => {}), set: (t, k, v) => { t[k] = v; return true; } });
const canvas = { getContext: () => ctx, width: 0, height: 0 }; const handlers = {};
const document = { getElementById: id => id === "c" ? canvas : el(id) };
const timers = []; const setTimeout = (f) => { timers.push(f); return timers.length; }, clearTimeout = () => {};
new Function("document", "ad", "addEventListener", "innerWidth", "innerHeight", "setTimeout", "clearTimeout", code)(document, { on: (ch, f) => handlers[ch] = f }, () => {}, 1920, 864, setTimeout, clearTimeout);
const cfg = (o) => handlers.cfg({ scale: 0.75, all: false, paused: false, hidden: false, plname: "1 团队", version: "1.8.0", hotkey: { "隐藏/显示": "F6" }, ...o });
const adv = { type: "advice", side: "R", seat: 7, my_turn: true, pre: "preview", ahead: 2, base: 0.6, rows: [{ key: "a", name: "影魔", p: 0.66, d: 0.06, box: [100, 100, 60, 60] }, { key: "b", name: "锚击", p: 0.64, d: 0.04, box: [200, 100, 60, 60] }] };
const active = { type: "state", phase: "active", ms: 20, current: { side: "L", idx: 0 }, me: { side: "R", idx: 2 }, taken: 3, poolOk: true, board: true };
let ok = true; const check = (what, cond) => { console.log(`${cond ? "✓" : "✗"} ${what}`); ok = ok && cond; };
const show = () => ({ status: els.status.textContent, toast: els.toast.style.display === "block" ? els.toast.textContent : "" });
cfg({});
check("启动(没有任何状态): 什么都不显示", show().status === "" && show().toast === "");
handlers.state({ type: "state", phase: "idle", idle: true, board: true, near: false });
check("游戏里画面被粗检当成像棋盘(检出格<40): 不显示", show().status === "");
handlers.state({ type: "state", phase: "idle", idle: true, board: true, waiting: true, near: true });
check("真看到选技棋盘但池子还没锁上: 显示\"正在识别\"", /正在识别池子/.test(show().status));
handlers.state(active); drawn = 0; handlers.advice(adv);
check("选技中: 状态行 + 推荐框都显示", /已选走 3/.test(show().status) && drawn > 0);
cfg({ hidden: true });
check("按 F6 隐藏: 状态行清空 + 弹 2 秒提示", show().status === "" && /已隐藏 · 识别照常运行\(F6 恢复显示\)/.test(show().toast));
drawn = 0; handlers.advice({ ...adv, base: 0.61 }); handlers.state({ ...active, taken: 4 });
check("隐藏期间照常收到新推荐/新状态, 但不画", drawn === 0 && show().status === "");
timers.splice(0).forEach(f => f());
check("2 秒后提示自动消失", show().toast === "");
drawn = 0; cfg({ hidden: false });
check("再按 F6: 立刻显示隐藏期间的最新结果", drawn > 0 && /已选走 4/.test(show().status) && /恢复显示\(F6 隐藏\)/.test(show().toast));
timers.splice(0).forEach(f => f()); cfg({ hidden: false, paused: true });
check("别的设置变化(暂停/模式切换)不弹隐藏提示", show().toast === "");
handlers.clear(); drawn = 0; handlers.state({ type: "state", phase: "idle", idle: true, board: false });
check("选技结束(棋盘消失): 推荐和状态行都清空", show().status === "" && drawn === 0);
console.log(ok ? "通过" : "失败"); process.exit(ok ? 0 : 1);
