"use strict";
const assert=require('assert/strict'),fs=require('fs'),path=require('path');
const code=fs.readFileSync(path.resolve(__dirname,'../overlay.html'),'utf8').split('<script>')[1].split('</script>')[0];
require("../frames.js");   // overlay.html 现在从 frames.js 取画框代码(挂在 globalThis.ADFrames)
let texts=[],colors=[];const handlers={},els={};
const ctx=new Proxy({measureText:()=>({width:100}),fillText:t=>{texts.push(t);colors.push([t,ctx.fillStyle]);},clearRect:()=>{texts=[];colors=[];}},{get:(t,k)=>t[k]||(()=>{})});
const canvas={getContext:()=>ctx};
const doc={getElementById:id=>id==='c'?canvas:(els[id]||=( {style:{},textContent:''}))};
new Function('document','ad','addEventListener','innerWidth','innerHeight','setTimeout','clearTimeout',code)(doc,{on:(k,f)=>handlers[k]=f},()=>{},1920,864,()=>1,()=>{});
const active={phase:'active',current:{side:'L',idx:0},me:{side:'L',idx:0},playerScores:Array.from({length:10},(_,i)=>({box:[0,100+i*20,112,176],parts:{main:.9,synergy:-.2,team:0,counter:.12},total:i===9?null:.82,heroKnown:true,skillCount:2,unknown:i===9?1:0}))};
handlers.cfg({scale:1,hidden:false});handlers.state(active);
assert.equal(texts.filter(t=>t.startsWith('组合')).length,10,'scores before advice');
assert.ok(texts.some(t=>t.includes('待认')));
handlers.computing({});assert.equal(texts.filter(t=>t==='组合明细').length,10,'independent of recommendation computation');
handlers.clear();assert.equal(texts.filter(t=>t==='组合明细').length,10,'recommendation clear keeps final draft scores');
handlers.cfg({scale:1,hidden:true});assert.equal(texts.length,0);
handlers.state(active);assert.equal(texts.length,0);
handlers.cfg({scale:1,hidden:false});assert.equal(texts.filter(t=>t==='组合明细').length,10);
handlers.state({...active,playerScores:active.playerScores.map(p=>({...p,total:1.23}))});
assert.equal(texts.filter(t=>t==='+1.23').length,10,'state-only correction redraws');
assert.ok(colors.some(([t,c])=>t==='+0.90'&&c==='#7ee0a8'),'positive green');
assert.ok(colors.some(([t,c])=>t==='-0.20'&&c==='#ff8585'),'negative red');
assert.ok(colors.some(([t,c])=>t==='0.00'&&c==='#dce8f2'),'zero neutral');
for(const label of ['基础','配合','队友','克制','合计'])assert.equal(texts.filter(t=>t===label).length,10);
handlers.cfg({scale:1,hidden:false,showPlayerScores:false,phase:'active'});
assert.equal(texts.length,0,'independent toggle hides scores');
handlers.advice({side:'L',seat:0,base:.5,rows:[]});
assert.ok(texts.some(t=>t.includes('推荐:')),'recommendations remain visible');
handlers.state(active);assert.ok(!texts.includes('组合明细'),'new state does not override toggle');
handlers.cfg({scale:1,hidden:false,showPlayerScores:true,phase:'active'});
assert.equal(texts.filter(t=>t==='组合明细').length,10,'toggle restores without waiting for state');
handlers.cfg({scale:1,hidden:false,showPlayerScores:true,phase:'idle'});
assert.equal(texts.length,0,'phase change hides immediately even before idle state');
handlers.clear();assert.equal(texts.length,0,'clear cannot revive scores in game');
handlers.cfg({scale:1,hidden:false,showPlayerScores:false,phase:'idle'});
handlers.state({phase:'idle',idle:true,board:false});
handlers.cfg({scale:1,hidden:false,showPlayerScores:false,phase:'active'});
handlers.state(active);assert.equal(texts.length,0,'disabled preference survives next draft');
handlers.cfg({scale:1,hidden:false,showPlayerScores:true,phase:'active'});
assert.equal(texts.filter(t=>t==='组合明细').length,10);
handlers.state({phase:'idle',idle:true,board:false});assert.equal(texts.length,0);
console.log('PASS scoreboard overlay: all seats, pre-advice, computing, clear, hidden, correction, idle');
